Basic:
    phoneme_type: False
    
    #only available when character mode triggered
    char_path: ./asset/dict/ko.json
    train_img_path: /home/jovyan/SharedVolume(readonly)/Datasets/Train
    
Model:
    hidden_size: 1024
    output_size: 512
    input_size: 3
    use_tp: True
    
Program:
    batch_size: 50
    epochs: 500
    learning_rate: 0.0005
    save_path: ./result/
    saved_model: ./result/char/model_para:False_0.0003.pth
