Basic:
    phoneme_type: True
    
    #only available when character mode triggered
    char_path: ./asset/dict/ko.json
    train_img_path: ./train_data/Datasets/Train/
    
Model:
    hidden_size: 1024
    output_size: 512
    input_size: 3
    use_tp: True
    
Program:
    batch_size: 2
    epochs: 500
    learning_rate: 0.0003
    save_path: ./result/
    saved_model: ./result/char/model_para:False_0.0003.pth

    
